#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.
cartridge_type="python-2.6"
source $OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/bin/activate
#echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/prbbook/manage.py celery worker --loglevel=INFO'"
#nohup python "$OPENSHIFT_REPO_DIR"wsgi/prbbook/manage.py celery worker --loglevel=INFO >> /dev/null &

echo "Перехожу в папку $OPENSHIFT_REPO_DIR/wsgi/prbbook/"
cd $OPENSHIFT_REPO_DIR/wsgi/prbbook/
pwd

function start {
    echo "Выполняю \"nohup ./manage.py celery worker --loglevel=INFO --logfile=./celery.log --pidfile=./celery.pid --quiet >> /dev/null & > /dev/null\""
    nohup ./manage.py celery worker --loglevel=INFO --logfile=./celery.log --pidfile=./celery.pid --quiet >> /dev/null & > /dev/null
} 

if [[ -e "./celery.pid" ]] 
then
    echo "Файл ./celery.pid присутствует"
    pid=`cat ./celery.pid`
    if [[ `ps -A | grep $pid` ]]
    then
       echo "Процесс указанный в файле ./celery.pid существует"
       echo "Выполняю \"kill -s HUP $pid\""
       kill -s HUP $pid
    else
       echo "Процесс указанный в файле ./celery.pid не существует"
       echo "Выполняю \"rm ./celery.pid\""
       rm ./celery.pid
       echo "Проверяю не запущены ли в системе веркеры celery"
       if [[ `ps -Af | grep "celery worker"` ]]
       then
          echo "В системе запущены процессы веркеров"
       else
          echo "В системе не запущены процессы веркеров"
          start
       fi
    fi
else
    echo "Файл ./celery.pid отсутствует"
    echo "Проверяю есть ли процессы celery worker"
    if [[ `ps -Af | grep "celery worker"`]]
    then
    	echo "Процессы существую. Необходимо послать сигнал для перезагрузки"
	else
		echo "Процессов не существует запускаю celery"
		start
	fi
fi

echo "Выхожу в изначальный каталог -"
cd -