#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.
cartridge_type="python-2.6"
source $OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/bin/activate

echo "Перехожу в папку $OPENSHIFT_REPO_DIR/wsgi/prbbook/"
cd $OPENSHIFT_REPO_DIR/wsgi/prbbook/
pwd

function start {
    echo "Выполняю \"nohup ./manage.py celery worker --loglevel=INFO --logfile=./celery.log --quiet >> /dev/null & > /dev/null\""
    nohup ./manage.py celery worker --loglevel=INFO --logfile=./celery.log --quiet >> /dev/null & > /dev/null
} 

echo "Проверяю есть ли процессы celery worker"
if [[ `ps -Af | grep "celery worker" | grep -v grep` ]]
then
	echo "Процессы существую. Необходимо послать сигнал для перезагрузки веркеров"
	echo "в случае если были изменены задания."
else
	echo "Процессов не существует запускаю celery"
	start
fi

echo "Выхожу в изначальный каталог -"
cd -